#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Remove all generated Cursor and Claude adapter files.

.DESCRIPTION
  Deletes generated adapter trees so .cursor/ and .claude/ stay clean in git.
  Keeps only pointer READMEs (and .claude/settings.local.json if present).

  Regenerate with:  powershell -File ai/scripts/sync-adapters.ps1

  Run from repo root:  powershell -File ai/scripts/clean-adapters.ps1
#>
[CmdletBinding()]
param(
  [string]$RepoRoot = ''
)

if (-not $RepoRoot) {
  $scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
  $RepoRoot = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
}

$ErrorActionPreference = 'Stop'

function Remove-IfExists([string]$RelativePath) {
  $full = Join-Path $RepoRoot $RelativePath
  if (Test-Path $full) {
    Remove-Item -Recurse -Force $full
    Write-Host "Removed $RelativePath"
    return $true
  }
  return $false
}

Write-Host "Repo root: $RepoRoot"
Write-Host 'Cleaning generated adapter folders...'
Write-Host ''

# Generated by sync-adapters.ps1 (also listed in .gitignore)
$generated = @(
  '.cursor\rules',
  '.cursor\agents',
  '.cursor\skills',
  '.claude\rules',
  '.claude\skills',
  '.claude\agents'
)

# Legacy copies / pointer trees from earlier layout (not generated anymore)
$legacy = @(
  '.cursor\context',
  '.cursor\examples',
  '.cursor\templates',
  '.cursor\checklists',
  '.cursor\prompts',
  '.cursor\mcp'
)

$removed = 0
foreach ($rel in ($generated + $legacy)) {
  if (Remove-IfExists $rel) { $removed++ }
}

Write-Host ''
Write-Host "Done. Removed $removed path(s)."
Write-Host ''
Write-Host 'Kept:'
Write-Host '  .cursor/README.md'
Write-Host '  .claude/README.md'
Write-Host '  .claude/settings.local.json (if present)'
Write-Host '  .cursor/mcp.json (if present - live MCP config, not generated)'
Write-Host ''
Write-Host 'To regenerate adapters:  powershell -File ai/scripts/sync-adapters.ps1'
